// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkwxjndgwuhmlhxrocip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprd3hqbmRnd3VobWxoeHJvY2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzUxMTgsImV4cCI6MjA2MDMxMTExOH0.OFauxGwGiPDZcKZn2EkK8Cm9zwDqBL47krgFcZnkgTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);