
/**
 * Represents a mini-game generated by the AI
 */
export interface MiniGame {
  /**
   * Title of the mini-game
   */
  title?: string;
  
  /**
   * HTML content of the mini-game
   */
  content: string;
  
  /**
   * Additional meta data
   */
  meta?: Record<string, any>;
}
